---
- name: Install packages
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ package }}"
  when:
    - ansible_facts.distribution == "RedHat"
    - ansible_facts.distribution_major_version == "7"
